### ISSUE TITLE
Server was killed with SIGSEGV

### ISSUE THREAD

**Issue by carlospliego** [trion-development/docker-ng-cli-e2e#3]
Stack Trace
```
[22:09:21] E/launcher - Server was killed with SIGSEGV
[22:09:21] E/launcher - Error: Server was killed with SIGSEGV
    at earlyTermination.catch.e (/app/node_modules/selenium-webdriver/remote/index.js:252:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/app/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/app/node_modules/selenium-webdriver/chrome.js:709:29)
    at Direct.getNewDriver (/app/node_modules/protractor/lib/driverProviders/direct.ts:90:25)
    at Runner.createBrowser (/app/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/app/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/app/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/app/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/app/node_modules/protractor/node_modules/q/q.js:796:13)
    at /app/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/app/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/app/node_modules/protractor/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

**Comment by everflux** [comment]
Can you provide a minimal reproducible testcase/repo?
